### ISSUE TITLE
Can't load auth.txt from outside of project folder

### ISSUE THREAD

**Issue by MrEliptik** [MrEliptik/godot_twitch_games#18]
To allow users to log in to twitch using the release version, we should load the credentials using the auth.txt from outside the `res://` folder, as its not included in this repo. 
Loading from `user://` is probably the easiest. It should be added to the documentation too.

**Comment by Drathal** [comment]
My thoughts on this:
Im coming from web dev. The standard / best practice there is to have a `.env` file inside of the project root. This file is by default ignored in .gitignore. So no one will share secrets or other stuff that should be private. To help devs setup this `.env` file often there is also an  `.env.example` file. In the dev documentation there will be a part that explains that you how to make a copy of that file and name it `.env`. Then in the `.env.example` file there are already all settings that are not secret as well as placeholders for things like tokens. 

So i would like to provide a `development.md` file where we start to put in all things that are important when you want to contribute to the project. One section could be what i described above (no mater if that config file then lives in the project itself or should be copied to the user directory).

When i think a step further, we maybe want a setup script. We should have an opinion on what type of script language we want to use and what can run on all worlds (linux/mac/pc). I think it is important to be aware that whatever this script language will be, it will add more complexity. For me personally i would just add a bash script that can help setup things. But thats my personal preference. That will force windows people to add another shell.
