### ISSUE TITLE
Auto join when someone is typing !fire

### ISSUE THREAD

**Issue by MrEliptik** [MrEliptik/godot_twitch_games#61]
Viewers can be frustrated because they don't realize they have to join first. Simply autojoin them when they're typing their first `!fire`

**Comment by Laozey** [comment]
Could this be solved by calling `spawn_viewer` there ?
https://github.com/MrEliptik/godot_twitch_games/blob/8cb6a12b319f2b8c8c4d7775191082b40047c6e2/scenes/games/cannon/cannon.gd#L79-L81

**Comment by MrEliptik** [comment]
Yes! Instead of returning, we could spawn the viewer
