### ISSUE TITLE
line break convention

### ISSUE THREAD

**Issue by Drathal** [MrEliptik/godot_twitch_games#74]
We should setup s config (could be .gitconfig) to NOT mix up line breaks.

At the moment we have mixed line breaks. This makes PR hard to read because of line that are marked as changed.

Here is one possible solution: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by MrEliptik** [comment]
I didn't realize this was a problem but you're right we should fix that. The per-repo solution inside a `.gitconfig` file seems to be good.

**Comment by Drathal** [comment]
I also found out that this also affects builds on Mac. Gift has the OAuth URL saved as multiline. But this can destroy the CallbackURL

**Comment by Drathal** [comment]
Ticket can be closed. We have a proper `.gitattributes`. We had some files that where older but now all file should be handled right
