### ISSUE TITLE
Godot Version

### ISSUE THREAD

**Issue by Drathal** [MrEliptik/godot_twitch_games#75]
Godot Version 4.1.3 stable is out

**Comment by MrEliptik** [comment]
It has been out for a while, right? I've been using it for the project for some time already. Do we need to do something special about it?

**Comment by Drathal** [comment]
We can just update i think. Maybe its more important that we put the version we are using into the readme?

**Comment by MrEliptik** [comment]
Yeah we can do that for sure 👍
